#!/bin/bash

docker run \
 -v /var/docker/Docker-Asterisk16/centos7/etc/asterisk:/etc/asterisk \
 -v /var/docker/Docker-Asterisk16/centos7/var/log/asterisk:/var/log/asterisk \
 -p 5060:5060 \
 --name pbx \
 -h pbx \
 --restart=always \
 -i -t "aster"
